spring.application.name=hameed-money-cli

# add datasource configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hmc-db
spring.datasource.username=hmc-user
spring.datasource.password=hmc-password
spring.datasource.hikari.schema=app_data
spring.datasource.driver-class-name=org.postgresql.Driver


# custom
hmc.report.output-dir=/hmc/reports
